# Uncomment the next line to define a global platform for your project
# platform :ios, ‘8.0’

target 'MusouSample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  # Remove the path param when release
  pod 'MusouKit',:path=>'../../MusouKit.podspec'

end
